# Generated by Django 4.2.7 on 2023-12-11 16:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boardAnwser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash256', models.TextField(default='a', max_length=255)),
                ('web_id', models.CharField(max_length=30)),
                ('answer_id', models.CharField(default='', max_length=30)),
                ('title', models.CharField(default=0, max_length=50)),
                ('text', models.TextField(default=0)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash256', models.TextField(default='a', max_length=255)),
                ('web_id', models.CharField(max_length=30)),
                ('title', models.CharField(default=0, max_length=50)),
                ('filed', models.CharField(choices=[('커뮤니티', '커뮤니티'), ('Qna', 'Qna'), ('공지사항12755555', '공지사항12755555')], default='커뮤니티', max_length=255)),
                ('text', models.TextField()),
                ('answer', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='gpt_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.TextField()),
                ('table', models.TextField()),
                ('text1', models.TextField()),
                ('answer', models.TextField()),
                ('report', models.TextField()),
                ('html', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='lecture1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contents_1', models.CharField(default='기초 교육', max_length=255)),
                ('Contents_2', models.CharField(default='', max_length=255)),
                ('Contents_3', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='lecture2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contents_1', models.CharField(default='분석 교육', max_length=255)),
                ('Contents_2', models.CharField(default='', max_length=255)),
                ('Contents_3', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='lecture3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contents_1', models.CharField(default='제작 교육', max_length=255)),
                ('Contents_2', models.CharField(default='', max_length=255)),
                ('Contents_3', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='lecture_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toggle', models.CharField(default='', max_length=255)),
                ('page', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
            ],
        ),
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemTitle', models.CharField(max_length=255)),
                ('problemInfo', models.CharField(max_length=150)),
                ('sha256', models.CharField(max_length=255)),
                ('Field', models.CharField(choices=[('InfoStealer', 'InfoStealer'), ('RAT', 'RAT'), ('Downloader/Dropper', 'Downloader/Dropper'), ('Ransomware', 'Ransomware'), ('Backdoor', 'Backdoor'), ('Scenario', 'Scenario')], default='InfoStealer', max_length=255)),
                ('level', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('status', models.CharField(default=0, max_length=255)),
                ('table', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='problem_exe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=150)),
                ('markdown', models.TextField(default='')),
                ('A', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('B', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('C', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('D', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('E', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('F', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
            ],
        ),
        migrations.CreateModel(
            name='problem_exe_Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default='', max_length=50)),
                ('name', models.TextField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(max_length=30)),
                ('pw', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('lec1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('lec2', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('lec3', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('A', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('B', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('C', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('D', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('E', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('F', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed', models.TextField(default='', max_length=50)),
                ('progress_value', models.TextField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user')),
            ],
        ),
    ]
