# Generated by Django 4.2.7 on 2023-12-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_boards_hash256'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardanwser',
            name='hash256',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='boards',
            name='hash256',
            field=models.CharField(default='', max_length=255),
        ),
    ]
