# Generated by Django 4.2.7 on 2023-12-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_boardanwser_hash256_boards_hash256'),
    ]

    operations = [
        migrations.CreateModel(
            name='virtualize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(default='', max_length=255)),
                ('vm_id', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='', max_length=3)),
            ],
        ),
    ]
