# Generated by Django 4.2.4 on 2023-10-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_remove_problem_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='Field',
            field=models.CharField(choices=[('InfoStealer', 'InfoStealer'), ('Adware', 'Adware'), ('Downloader/Dropper', 'Downloader/Dropper'), ('Ransomware', 'Ransomware'), ('Backdoor', 'Backdoor')], default='InfoStealer', max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='level',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
