# Generated by Django 4.2.4 on 2023-10-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_problem_field_alter_problem_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='Field',
            field=models.CharField(choices=[('InfoStealer', 'InfoStealer'), ('Adware', 'Adware'), ('Downloader/Dropper', 'Downloader/Dropper'), ('Ransomware', 'Ransomware'), ('Backdoor', 'Backdoor'), ('Scenario', 'Scenario')], default='InfoStealer', max_length=255),
        ),
    ]
