# Generated by Django 4.2.4 on 2023-10-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_problem_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='lecture3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contents_1', models.CharField(default='제작 교육', max_length=255)),
                ('Contents_2', models.CharField(default='', max_length=255)),
                ('Contents_3', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='lecture1',
            name='Contents_1',
            field=models.CharField(default='기초 교육', max_length=255),
        ),
        migrations.AlterField(
            model_name='lecture2',
            name='Contents_1',
            field=models.CharField(default='분석 교육', max_length=255),
        ),
    ]
