# Generated by Django 4.2.6 on 2023-10-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_lecture3_alter_lecture1_contents_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='answer',
        ),
        migrations.AddField(
            model_name='board',
            name='title',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
