# Generated by Django 4.2.6 on 2023-10-27 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_remove_board_answer_board_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)]),
        ),
    ]
