# Generated by Django 4.2.6 on 2023-10-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_board_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='filed',
            field=models.CharField(choices=[('커뮤니티', '커뮤니티'), ('Qna', 'Qna'), ('공지사항', '공지사항')], default='커뮤니티', max_length=255),
        ),
    ]
