# Generated by Django 4.2.6 on 2023-10-27 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_alter_board_filed'),
    ]

    operations = [
        migrations.CreateModel(
            name='boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(max_length=30)),
                ('title', models.CharField(default=0, max_length=50)),
                ('filed', models.CharField(choices=[('커뮤니티', '커뮤니티'), ('Qna', 'Qna'), ('공지사항', '공지사항')], default='커뮤니티', max_length=255)),
                ('text', models.TextField()),
                ('count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
            ],
        ),
    ]
