# Generated by Django 4.2.6 on 2023-10-27 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_boards'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
