# Generated by Django 4.2.6 on 2023-10-27 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_boards_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='answer',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)]),
        ),
    ]
