# Generated by Django 4.2.6 on 2023-10-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_boards_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardanwser',
            name='text',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='boardanwser',
            name='title',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
