# Generated by Django 4.2.6 on 2023-10-28 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_boardanwser_text_boardanwser_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardanwser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
