# Generated by Django 4.2.7 on 2023-11-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_boardanwser_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='gpt_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.TextField()),
                ('table', models.TextField()),
                ('text1', models.TextField()),
                ('answer', models.TextField()),
                ('report', models.TextField()),
                ('html', models.TextField()),
            ],
        ),
    ]
