# Generated by Django 4.2.7 on 2023-11-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_gpt_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpt_report',
            name='answer',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='gpt_report',
            name='html',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='gpt_report',
            name='lecture',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='gpt_report',
            name='report',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='gpt_report',
            name='table',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='gpt_report',
            name='text1',
            field=models.TextField(default=0),
        ),
    ]
