# Generated by Django 4.2.7 on 2023-11-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_alter_gpt_report_answer_alter_gpt_report_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpt_report',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gpt_report',
            name='html',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gpt_report',
            name='lecture',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gpt_report',
            name='report',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gpt_report',
            name='table',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gpt_report',
            name='text1',
            field=models.TextField(),
        ),
    ]
