# Generated by Django 4.2.7 on 2023-11-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_alter_gpt_report_answer_alter_gpt_report_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpt_report',
            name='lecture',
            field=models.TextField(choices=[('1', '기초강의'), ('2', '제작강의'), ('3', '분석사항')]),
        ),
    ]
