# Generated by Django 4.2.7 on 2023-11-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_alter_gpt_report_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpt_report',
            name='lecture',
            field=models.TextField(),
        ),
    ]
