# Generated by Django 4.2.7 on 2023-11-08 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_alter_gpt_report_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpt_report',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
