# Generated by Django 4.2.7 on 2023-11-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_remove_progress_filed_progress_filed1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='filed1',
        ),
        migrations.AddField(
            model_name='progress',
            name='filed',
            field=models.TextField(default='', max_length=50),
        ),
    ]
