# Generated by Django 4.2.7 on 2023-11-30 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_remove_progress_filed1_progress_filed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lec1',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='user',
            name='lec2',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='user',
            name='lec3',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)]),
        ),
    ]
