# Generated by Django 4.2.7 on 2023-12-02 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_alter_problem_exe_a_alter_problem_exe_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='A',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='user',
            name='B',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='user',
            name='C',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='user',
            name='E',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='user',
            name='F',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='user',
            name='G',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)]),
        ),
    ]
