# Generated by Django 4.2.7 on 2023-12-02 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_user_a_user_b_user_c_user_e_user_f_user_g'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='G',
        ),
        migrations.AddField(
            model_name='user',
            name='D',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)]),
        ),
    ]
