# Generated by Django 4.2.7 on 2023-12-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_alter_problem_exe_progress_problem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem_exe_progress',
            old_name='problem',
            new_name='user',
        ),
        migrations.AddField(
            model_name='problem_exe_progress',
            name='name',
            field=models.TextField(default='', max_length=50),
        ),
    ]
