# Generated by Django 4.2.7 on 2023-12-02 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_rename_problem_problem_exe_progress_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='problem_exe_Progress',
        ),
    ]
