# Generated by Django 4.2.7 on 2023-12-02 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_problem_exe_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem_exe',
            name='G',
        ),
        migrations.AddField(
            model_name='problem_exe',
            name='D',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)]),
        ),
    ]
