# Generated by Django 4.2.7 on 2023-12-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_remove_problem_exe_g_problem_exe_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_exe_progress',
            name='user',
            field=models.TextField(default='', max_length=50),
        ),
    ]
