# Generated by Django 4.2.7 on 2023-12-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_alter_problem_exe_progress_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='lecture_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.CharField(default='제작 교육', max_length=255)),
                ('Contents', models.TextField(default='')),
            ],
        ),
    ]
