# Generated by Django 4.2.7 on 2023-12-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0050_lecture_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture_content',
            name='lecture',
            field=models.CharField(default='', max_length=255),
        ),
    ]
