# Generated by Django 4.2.7 on 2023-12-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0051_alter_lecture_content_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture_content',
            name='toggle',
            field=models.CharField(default='', max_length=255),
        ),
    ]
