# Generated by Django 4.2.7 on 2023-12-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0052_lecture_content_toggle'),
    ]

    operations = [
        migrations.CreateModel(
            name='lecture1_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contents_name', models.CharField(default='', max_length=255)),
                ('left_file', models.FileField(blank=True, null=True, upload_to='web/static/web/lecture1/')),
                ('right_file', models.FileField(blank=True, null=True, upload_to='web/static/web/lecture1')),
            ],
        ),
    ]
