# Generated by Django 4.2.7 on 2023-12-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_lecture1_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='lecture2_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contents_name', models.CharField(default='', max_length=255)),
                ('left_file', models.FileField(blank=True, null=True, upload_to='web/static/web/lecture2/')),
                ('right_file', models.FileField(blank=True, null=True, upload_to='web/static/web/lecture2')),
            ],
        ),
        migrations.CreateModel(
            name='lecture3_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contents_name', models.CharField(default='', max_length=255)),
                ('left_file', models.FileField(blank=True, null=True, upload_to='web/static/web/lecture3/')),
                ('right_file', models.FileField(blank=True, null=True, upload_to='web/static/web/lecture3')),
            ],
        ),
    ]
