# Generated by Django 4.2.7 on 2023-12-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_lecture2_content_lecture3_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem_exe',
            name='markdown',
            field=models.TextField(default=''),
        ),
    ]
