# Generated by Django 4.2.7 on 2023-12-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0055_problem_exe_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardanwser',
            name='answer_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
