# Generated by Django 4.2.7 on 2023-12-07 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0056_boardanwser_answer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='lecture_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toggle', models.CharField(default='', max_length=255)),
                ('page', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
            ],
        ),
        migrations.DeleteModel(
            name='board',
        ),
        migrations.DeleteModel(
            name='lecture1_content',
        ),
        migrations.DeleteModel(
            name='lecture2_content',
        ),
        migrations.DeleteModel(
            name='lecture3_content',
        ),
        migrations.DeleteModel(
            name='lecture_content',
        ),
        migrations.DeleteModel(
            name='scenario',
        ),
    ]
